openapi:  3.0.2
info:

get:
    tags:
        - competitions
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        List of Competitions:
                            value: |-
                                [
                                    "Võistlus"
                                    "Meistrivõistlus"
                                    ]
            description: Returns a list of competitions
    operationId: '#184267953'
    summary: Get a list of all competitions
    description: Returns a list of all competitions in API
post:
    tags:
        - competitions
    responses:
        '201':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        Example of entry:
                            value:
                                - Comp name
                                - Comp date
            description: Creates new entry with entered variables
    operationId: '#184268298'
    summary: Add competitions and add info on lines for competitions
    description: |
        Create new competition, add variables

        
    tags:
        - details
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        Full details of a given competition:
                            value:
                                - 2324234
                                - Meistrivõistlus
                                - 20.04.2023
                                - Slaalom
                                - 5
                                - jama
                                - Tartu
                                - Bossworm
            description: Returns full details of a given id competition
        '404':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/error'
                    examples:
                        Competition /w+ was not found:
                            value:
                                error: Competition \w+ was not found in competition array
            description: Competition was not found in competitions array
    operationId: '#184268001'
    summary: Get full details of a competition
    description: Returns full details of a given id competition
parameters:
    -
        name: id
        schema:
            type: integer
        in: path
        required: true
